name: XLib-Runtime
main: ${pluginClass}
version: ${project.version}${buildNo}
author: Daniel Saukel
description: "${project.parent.description}"
website: ${project.url}
commands:
  xlib:
    description: XLib core command.
    aliases: [itemsxl, ixl]
  givehead:
    description: Gives a head to a player.
    aliases: [headlib,gh]
    permission: headlib.give
    usage: "Usage: /<command> ([player name (=sender)]) (head:[head name]) (uuid:[owner UUID]) (textureValue:[texture value]) (amount:[amount]) (name and lore...)"
api-version: 1.13
