name: ExamplePlugin
main: de.erethon.xlib.exampleplugin.ExamplePlugin
version: ${project.version}${buildNo}
author: Daniel Saukel
description: "Example plugin for XLib v${project.parent.version}."
website: ${project.url}
commands:
  giveexample:
    description: "Gives example items."
    aliases: [givex]
  guiexample:
    description: "Opens example menu."
    aliases: [guix]
api-version: 1.13
